exclude: (^|/)\.idea/|(^|/)wailsjs/|.*\.md5$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.md$'
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: pretty-format-json
        exclude: '^(frontend/package-lock\.json|frontend/package\.json|build/windows/info\.json|wails\.json)$'
        args:
          - "--autofix"
          - "--no-ensure-ascii"

  # Shell scripts
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  # Python
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        files: python/
        args: [ "--profile", "black" ]
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        files: python/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff
        files: python/
        args: [ --fix ]
      - id: ruff-format
        files: python/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.16.1'
    hooks:
      - id: mypy
        files: python/

  # UV
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.20
    hooks:
      - id: uv-lock
        files: python/pyproject.toml
        args: [--project, python]
      - id: uv-export
        files: python/pyproject.toml
        args: [--project, python]

  # Golang
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.2.2
    hooks:
      - id: golangci-lint
        files: \.go$

  # Frontend
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry:  npm --prefix frontend run prettier-write
        language: system
        files: frontend/
        pass_filenames: false

  - repo: local
    hooks:
      - id: svelte-check
        name: svelte-check
        entry: npm --prefix frontend run check
        language: system
        files: frontend/
        pass_filenames: false
      - id: image-check
        name: Ensure only PNG images
        language: fail
        entry: 'Only PNG images are allowed. Invalid files:'
        files: \.(jpe?g|bmp|gif|webp|tiff?)$
        types: [file]
