// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEditableGameConfig(arg1) {
  return window['go']['main']['App']['GetEditableGameConfig'](arg1);
}

export function GetEditableMainConfig() {
  return window['go']['main']['App']['GetEditableMainConfig']();
}

export function GetRunningSupportedGame() {
  return window['go']['main']['App']['GetRunningSupportedGame']();
}

export function IsGameProcessRunning() {
  return window['go']['main']['App']['IsGameProcessRunning']();
}

export function SaveAFKJourneyConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveAFKJourneyConfig'](arg1, arg2);
}

export function SaveMainConfig(arg1) {
  return window['go']['main']['App']['SaveMainConfig'](arg1);
}

export function StartGameProcess(arg1, arg2) {
  return window['go']['main']['App']['StartGameProcess'](arg1, arg2);
}

export function TerminateGameProcess() {
  return window['go']['main']['App']['TerminateGameProcess']();
}
