// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.UpdateInfo>}
 */
export function CheckForUpdates() {
    return $Call.ByID(1249893213).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} downloadURL
 * @returns {$CancellablePromise<void>}
 */
export function DownloadUpdate(downloadURL) {
    return $Call.ByID(674014119, downloadURL);
}

/**
 * @returns {$CancellablePromise<$models.Changelog[]>}
 */
export function GetChangelogs() {
    return $Call.ByID(241706445).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $models.Changelog.createFrom;
const $$createType2 = $Create.Array($$createType1);
