// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ipc$0 from "../ipc/models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function Debug() {
    return $Call.ByID(2279654713);
}

/**
 * @returns {$CancellablePromise<ipc$0.GameGUI | null>}
 */
export function GetGameGUI() {
    return $Call.ByID(1729333075).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {ipc$0.GameGUI} game
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetGameSettingsForm(game) {
    return $Call.ByID(3164261351, game).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function KillGameProcess() {
    return $Call.ByID(4018216029);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SaveDebugZip() {
    return $Call.ByID(2087350553);
}

/**
 * @param {{ [_: string]: any }} gameSettings
 * @returns {$CancellablePromise<ipc$0.GameGUI | null>}
 */
export function SaveGameSettings(gameSettings) {
    return $Call.ByID(3663949236, gameSettings).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string[]} args
 * @returns {$CancellablePromise<void>}
 */
export function StartGameProcess(args) {
    return $Call.ByID(2571463401, args);
}

// Private type creation functions
const $$createType0 = ipc$0.GameGUI.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
