// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AdvancedSettings {
    /**
     * Creates a new AdvancedSettings instance.
     * @param {Partial<AdvancedSettings>} [$$source = {}] - The source object to create the AdvancedSettings.
     */
    constructor($$source = {}) {
        if (!("ADB Server Host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ADB Server Host"] = "";
        }
        if (!("ADB Server Port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ADB Server Port"] = 0;
        }
        if (!("AutoPlayer Host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["AutoPlayer Host"] = "";
        }
        if (!("AutoPlayer Port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["AutoPlayer Port"] = 0;
        }
        if (!("Streaming FPS" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Streaming FPS"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AdvancedSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AdvancedSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AdvancedSettings(/** @type {Partial<AdvancedSettings>} */($$parsedSource));
    }
}

export class DeviceSettings {
    /**
     * Creates a new DeviceSettings instance.
     * @param {Partial<DeviceSettings>} [$$source = {}] - The source object to create the DeviceSettings.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("Resize Display (Phone/Tablet only)" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Resize Display (Phone/Tablet only)"] = false;
        }
        if (!("Device Streaming (disable for slow PCs)" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Device Streaming (disable for slow PCs)"] = false;
        }
        if (!("Enable Hardware Decoding" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Enable Hardware Decoding"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceSettings(/** @type {Partial<DeviceSettings>} */($$parsedSource));
    }
}

export class GeneralSettings {
    /**
     * Creates a new GeneralSettings instance.
     * @param {Partial<GeneralSettings>} [$$source = {}] - The source object to create the GeneralSettings.
     */
    constructor($$source = {}) {
        if (!("Advanced" in $$source)) {
            /**
             * @member
             * @type {AdvancedSettings}
             */
            this["Advanced"] = (new AdvancedSettings());
        }
        if (!("Device" in $$source)) {
            /**
             * @member
             * @type {DeviceSettings}
             */
            this["Device"] = (new DeviceSettings());
        }
        if (!("Update" in $$source)) {
            /**
             * @member
             * @type {UpdateSettings}
             */
            this["Update"] = (new UpdateSettings());
        }
        if (!("Logging" in $$source)) {
            /**
             * @member
             * @type {LoggingSettings}
             */
            this["Logging"] = (new LoggingSettings());
        }
        if (!("User Interface" in $$source)) {
            /**
             * @member
             * @type {UISettings}
             */
            this["User Interface"] = (new UISettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GeneralSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GeneralSettings}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Advanced" in $$parsedSource) {
            $$parsedSource["Advanced"] = $$createField0_0($$parsedSource["Advanced"]);
        }
        if ("Device" in $$parsedSource) {
            $$parsedSource["Device"] = $$createField1_0($$parsedSource["Device"]);
        }
        if ("Update" in $$parsedSource) {
            $$parsedSource["Update"] = $$createField2_0($$parsedSource["Update"]);
        }
        if ("Logging" in $$parsedSource) {
            $$parsedSource["Logging"] = $$createField3_0($$parsedSource["Logging"]);
        }
        if ("User Interface" in $$parsedSource) {
            $$parsedSource["User Interface"] = $$createField4_0($$parsedSource["User Interface"]);
        }
        return new GeneralSettings(/** @type {Partial<GeneralSettings>} */($$parsedSource));
    }
}

export class LoggingSettings {
    /**
     * Creates a new LoggingSettings instance.
     * @param {Partial<LoggingSettings>} [$$source = {}] - The source object to create the LoggingSettings.
     */
    constructor($$source = {}) {
        if (!("Log Level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Log Level"] = "";
        }
        if (!("Debug Screenshot Limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Debug Screenshot Limit"] = 0;
        }
        if (!("Task Log Limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Task Log Limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoggingSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LoggingSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoggingSettings(/** @type {Partial<LoggingSettings>} */($$parsedSource));
    }
}

export class UISettings {
    /**
     * Creates a new UISettings instance.
     * @param {Partial<UISettings>} [$$source = {}] - The source object to create the UISettings.
     */
    constructor($$source = {}) {
        if (!("Theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Theme"] = "";
        }
        if (!("Language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Language"] = "";
        }
        if (!("Close button should minimize the window" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Close button should minimize the window"] = false;
        }
        if (!("Enable Notifications" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Enable Notifications"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UISettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UISettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UISettings(/** @type {Partial<UISettings>} */($$parsedSource));
    }
}

export class UpdateSettings {
    /**
     * Creates a new UpdateSettings instance.
     * @param {Partial<UpdateSettings>} [$$source = {}] - The source object to create the UpdateSettings.
     */
    constructor($$source = {}) {
        if (!("Automatically download updates" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Automatically download updates"] = false;
        }
        if (!("Download Alpha updates" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Download Alpha updates"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateSettings(/** @type {Partial<UpdateSettings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = AdvancedSettings.createFrom;
const $$createType1 = DeviceSettings.createFrom;
const $$createType2 = UpdateSettings.createFrom;
const $$createType3 = LoggingSettings.createFrom;
const $$createType4 = UISettings.createFrom;
