// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetGeneralSettings returns the current general settings
 * @returns {$CancellablePromise<$models.GeneralSettings>}
 */
export function GetGeneralSettings() {
    return $Call.ByID(3364062565).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetGeneralSettingsForm() {
    return $Call.ByID(455517895).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * LoadGeneralSettings reloads the general settings
 * @returns {$CancellablePromise<$models.GeneralSettings>}
 */
export function LoadGeneralSettings() {
    return $Call.ByID(4257029565).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.GeneralSettings} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveGeneralSettings(settings) {
    return $Call.ByID(31465946, settings);
}

// Private type creation functions
const $$createType0 = $models.GeneralSettings.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
